/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PublicRouteImport } from "./routes/_public"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as UserSettingsRouteImport } from "./routes/user/settings"
import { Route as GroupsCreateRouteImport } from "./routes/groups/create"
import { Route as AuthSignUpRouteImport } from "./routes/_auth/sign-up"
import { Route as AuthResetPasswordRouteImport } from "./routes/_auth/reset-password"
import { Route as AuthLoginRouteImport } from "./routes/_auth/login"
import { Route as GroupsGroupIdViewRouteImport } from "./routes/groups/$groupId/view"
import { Route as GroupsGroupIdNotificationsRouteImport } from "./routes/groups/$groupId/notifications"
import { Route as GroupsGroupIdEditRouteImport } from "./routes/groups/$groupId/edit"
import { Route as PublicJoinMembershipIdRouteImport } from "./routes/_public/join.$membershipId"
import { Route as GroupsGroupIdMeetingsMeetingIdViewRouteImport } from "./routes/groups/$groupId/meetings/$meetingId/view"
import { Route as GroupsGroupIdMeetingsMeetingIdEditRouteImport } from "./routes/groups/$groupId/meetings/$meetingId/edit"

const PublicRoute = PublicRouteImport.update({
  id: "/_public",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: "/user/settings",
  path: "/user/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsCreateRoute = GroupsCreateRouteImport.update({
  id: "/groups/create",
  path: "/groups/create",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any)
const GroupsGroupIdViewRoute = GroupsGroupIdViewRouteImport.update({
  id: "/groups/$groupId/view",
  path: "/groups/$groupId/view",
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdNotificationsRoute =
  GroupsGroupIdNotificationsRouteImport.update({
    id: "/groups/$groupId/notifications",
    path: "/groups/$groupId/notifications",
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdEditRoute = GroupsGroupIdEditRouteImport.update({
  id: "/groups/$groupId/edit",
  path: "/groups/$groupId/edit",
  getParentRoute: () => rootRouteImport,
} as any)
const PublicJoinMembershipIdRoute = PublicJoinMembershipIdRouteImport.update({
  id: "/join/$membershipId",
  path: "/join/$membershipId",
  getParentRoute: () => PublicRoute,
} as any)
const GroupsGroupIdMeetingsMeetingIdViewRoute =
  GroupsGroupIdMeetingsMeetingIdViewRouteImport.update({
    id: "/groups/$groupId/meetings/$meetingId/view",
    path: "/groups/$groupId/meetings/$meetingId/view",
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdMeetingsMeetingIdEditRoute =
  GroupsGroupIdMeetingsMeetingIdEditRouteImport.update({
    id: "/groups/$groupId/meetings/$meetingId/edit",
    path: "/groups/$groupId/meetings/$meetingId/edit",
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof AuthLoginRoute
  "/reset-password": typeof AuthResetPasswordRoute
  "/sign-up": typeof AuthSignUpRoute
  "/groups/create": typeof GroupsCreateRoute
  "/user/settings": typeof UserSettingsRoute
  "/join/$membershipId": typeof PublicJoinMembershipIdRoute
  "/groups/$groupId/edit": typeof GroupsGroupIdEditRoute
  "/groups/$groupId/notifications": typeof GroupsGroupIdNotificationsRoute
  "/groups/$groupId/view": typeof GroupsGroupIdViewRoute
  "/groups/$groupId/meetings/$meetingId/edit": typeof GroupsGroupIdMeetingsMeetingIdEditRoute
  "/groups/$groupId/meetings/$meetingId/view": typeof GroupsGroupIdMeetingsMeetingIdViewRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof AuthLoginRoute
  "/reset-password": typeof AuthResetPasswordRoute
  "/sign-up": typeof AuthSignUpRoute
  "/groups/create": typeof GroupsCreateRoute
  "/user/settings": typeof UserSettingsRoute
  "/join/$membershipId": typeof PublicJoinMembershipIdRoute
  "/groups/$groupId/edit": typeof GroupsGroupIdEditRoute
  "/groups/$groupId/notifications": typeof GroupsGroupIdNotificationsRoute
  "/groups/$groupId/view": typeof GroupsGroupIdViewRoute
  "/groups/$groupId/meetings/$meetingId/edit": typeof GroupsGroupIdMeetingsMeetingIdEditRoute
  "/groups/$groupId/meetings/$meetingId/view": typeof GroupsGroupIdMeetingsMeetingIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_auth": typeof AuthRouteWithChildren
  "/_public": typeof PublicRouteWithChildren
  "/_auth/login": typeof AuthLoginRoute
  "/_auth/reset-password": typeof AuthResetPasswordRoute
  "/_auth/sign-up": typeof AuthSignUpRoute
  "/groups/create": typeof GroupsCreateRoute
  "/user/settings": typeof UserSettingsRoute
  "/_public/join/$membershipId": typeof PublicJoinMembershipIdRoute
  "/groups/$groupId/edit": typeof GroupsGroupIdEditRoute
  "/groups/$groupId/notifications": typeof GroupsGroupIdNotificationsRoute
  "/groups/$groupId/view": typeof GroupsGroupIdViewRoute
  "/groups/$groupId/meetings/$meetingId/edit": typeof GroupsGroupIdMeetingsMeetingIdEditRoute
  "/groups/$groupId/meetings/$meetingId/view": typeof GroupsGroupIdMeetingsMeetingIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/reset-password"
    | "/sign-up"
    | "/groups/create"
    | "/user/settings"
    | "/join/$membershipId"
    | "/groups/$groupId/edit"
    | "/groups/$groupId/notifications"
    | "/groups/$groupId/view"
    | "/groups/$groupId/meetings/$meetingId/edit"
    | "/groups/$groupId/meetings/$meetingId/view"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/reset-password"
    | "/sign-up"
    | "/groups/create"
    | "/user/settings"
    | "/join/$membershipId"
    | "/groups/$groupId/edit"
    | "/groups/$groupId/notifications"
    | "/groups/$groupId/view"
    | "/groups/$groupId/meetings/$meetingId/edit"
    | "/groups/$groupId/meetings/$meetingId/view"
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/_public"
    | "/_auth/login"
    | "/_auth/reset-password"
    | "/_auth/sign-up"
    | "/groups/create"
    | "/user/settings"
    | "/_public/join/$membershipId"
    | "/groups/$groupId/edit"
    | "/groups/$groupId/notifications"
    | "/groups/$groupId/view"
    | "/groups/$groupId/meetings/$meetingId/edit"
    | "/groups/$groupId/meetings/$meetingId/view"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  GroupsCreateRoute: typeof GroupsCreateRoute
  UserSettingsRoute: typeof UserSettingsRoute
  GroupsGroupIdEditRoute: typeof GroupsGroupIdEditRoute
  GroupsGroupIdNotificationsRoute: typeof GroupsGroupIdNotificationsRoute
  GroupsGroupIdViewRoute: typeof GroupsGroupIdViewRoute
  GroupsGroupIdMeetingsMeetingIdEditRoute: typeof GroupsGroupIdMeetingsMeetingIdEditRoute
  GroupsGroupIdMeetingsMeetingIdViewRoute: typeof GroupsGroupIdMeetingsMeetingIdViewRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_public": {
      id: "/_public"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/user/settings": {
      id: "/user/settings"
      path: "/user/settings"
      fullPath: "/user/settings"
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/groups/create": {
      id: "/groups/create"
      path: "/groups/create"
      fullPath: "/groups/create"
      preLoaderRoute: typeof GroupsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth/sign-up": {
      id: "/_auth/sign-up"
      path: "/sign-up"
      fullPath: "/sign-up"
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/reset-password": {
      id: "/_auth/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/login": {
      id: "/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    "/groups/$groupId/view": {
      id: "/groups/$groupId/view"
      path: "/groups/$groupId/view"
      fullPath: "/groups/$groupId/view"
      preLoaderRoute: typeof GroupsGroupIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/groups/$groupId/notifications": {
      id: "/groups/$groupId/notifications"
      path: "/groups/$groupId/notifications"
      fullPath: "/groups/$groupId/notifications"
      preLoaderRoute: typeof GroupsGroupIdNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/groups/$groupId/edit": {
      id: "/groups/$groupId/edit"
      path: "/groups/$groupId/edit"
      fullPath: "/groups/$groupId/edit"
      preLoaderRoute: typeof GroupsGroupIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_public/join/$membershipId": {
      id: "/_public/join/$membershipId"
      path: "/join/$membershipId"
      fullPath: "/join/$membershipId"
      preLoaderRoute: typeof PublicJoinMembershipIdRouteImport
      parentRoute: typeof PublicRoute
    }
    "/groups/$groupId/meetings/$meetingId/view": {
      id: "/groups/$groupId/meetings/$meetingId/view"
      path: "/groups/$groupId/meetings/$meetingId/view"
      fullPath: "/groups/$groupId/meetings/$meetingId/view"
      preLoaderRoute: typeof GroupsGroupIdMeetingsMeetingIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/groups/$groupId/meetings/$meetingId/edit": {
      id: "/groups/$groupId/meetings/$meetingId/edit"
      path: "/groups/$groupId/meetings/$meetingId/edit"
      fullPath: "/groups/$groupId/meetings/$meetingId/edit"
      preLoaderRoute: typeof GroupsGroupIdMeetingsMeetingIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicJoinMembershipIdRoute: typeof PublicJoinMembershipIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicJoinMembershipIdRoute: PublicJoinMembershipIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  GroupsCreateRoute: GroupsCreateRoute,
  UserSettingsRoute: UserSettingsRoute,
  GroupsGroupIdEditRoute: GroupsGroupIdEditRoute,
  GroupsGroupIdNotificationsRoute: GroupsGroupIdNotificationsRoute,
  GroupsGroupIdViewRoute: GroupsGroupIdViewRoute,
  GroupsGroupIdMeetingsMeetingIdEditRoute:
    GroupsGroupIdMeetingsMeetingIdEditRoute,
  GroupsGroupIdMeetingsMeetingIdViewRoute:
    GroupsGroupIdMeetingsMeetingIdViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
